// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uscagdpxrfhdmjexagtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzY2FnZHB4cmZoZG1qZXhhZ3RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjgxOTQsImV4cCI6MjA3MjM0NDE5NH0.XReznBsxQuTfurP9bjIyNTU2inhb7SeRDRkNEhDBbWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});